name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build_test_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Prepare reports folder
        run: mkdir -p reports

      - name: Lint
        run: npm run lint

      - name: Unit tests + coverage
        run: npm run test:coverage

      - name: Metrics
        run: npm run metrics

      - name: Bad smell summary
        run: npm run smells

      - name: Mutation tests
        run: npm run mutation

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
